[manifest]
group-filter = ["-babblesim", "-optional", "-testing"]

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/zephyrproject-rtos/zephyr"
revision = "fb350217cc199e7e6c5a40b4e50a04adbf038f8b"
clone-depth = 1
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-z54vCKca+N1djr+qwrCwesE8wFhqGlwdq1GSVWmI6Ys="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-nTehISN0pu9gnOZMpGaBQ3DFmNxAqAZPGpvbKfEM35o="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "4dea410729da817a464f778533eb721473262e5b"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-xgRcp9p8kQqTKcI8FygFRfBuF3efq9KAPQa+V1XtAMQ="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "8f5ca347843363882619d8f96c00d8dbd88a8e79"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-MuXfpmEE3z0ZOtfjp93aAh/7xZhShmHzwHC5nyN2QQg="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/zephyrproject-rtos/mbedtls"
revision = "c5b06d89c9c498d8fc8659ce31f7e53137b6270f"
path = "modules/crypto/mbedtls"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-LSAC9ofincsigiBboMGFkh5dJL3rNWRLcI6oECIhq/U="

[[manifest.projects]]
name = "nrf_hw_models"
url = "https://github.com/zephyrproject-rtos/nrf_hw_models"
revision = "cf40f6dc7fc441ee6848ea2e177c4522588c1b8c"
path = "modules/bsim_hw_models/nrf_hw_models"

[manifest.projects.nix]
hash = "sha256-/1Mh3R2cRrWBUyBbYiMKrqb+e67SQaH7eNE31EjdLJg="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "50892fdbcf2f570e67baa72b8894a66b16946f72"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-EyrMOzsD8hClcAc778TsBe3dEFMtRAAeLzPxYK8NRcQ="

[manifest.self]
path = "app"
