manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      revision: main
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - mbedtls
          - nrf_hw_models
          - segger

  self:
    path: app
